const GalleryTypes = {
  GALLERY_FETCH_START: 'GALLERY_FETCH_START',
  GALLERY_FETCH_SUCCESS: 'GALLERY_FETCH_SUCCESS',
  GALLERY_FETCH_FAILURE: 'GALLERY_FETCH_FAILURE',
};

export default GalleryTypes;
