const ContactFormTypes = {
  CONTACT_FORM_SUBMIT_START: "CONTACT_FORM_SUBMIT_START",
  CONTACT_FORM_SUBMIT_SUCCESS: "CONTACT_FORM_SUBMIT_SUCCESS",
  CONTACT_FORM_SUBMIT_FAILURE: "CONTACT_FORM_SUBMIT_FAILURE",
};

export default ContactFormTypes;
