const ProjectsTypes = {
  PROJECTS_FETCH_START: "PROJECTS_FETCH_START",
  PROJECTS_FETCH_SUCCESS: "PROJECTS_FETCH_SUCCESS",
  PROJECTS_FETCH_FAILURE: "PROJECTS_FETCH_FAILURE",
};

export default ProjectsTypes;
