const ProjectsTypes = {
  PROJECTS_FETCH_START: "PROJECTS_FETCH_START",
  PROJECTS_FETCH_SUCCESS: "PROJECTS_FETCH_SUCCESS",
  PROJECTS_FETCH_FAILURE: "PROJECTS_FETCH_FAILURE",
  CHANGE_SELECTED_PROJECT_LIST_OPTION: "CHANGE_SELECTED_PROJECT_LIST_OPTION",
};

export default ProjectsTypes;
